/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_onion_ffmpeg_FfmpegHelp */

#ifndef _Included_com_onion_ffmpeg_FfmpegHelp
#define _Included_com_onion_ffmpeg_FfmpegHelp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_onion_ffmpeg_FfmpegHelp
 * Method:    urlprotocolinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_onion_ffmpeg_FfmpegHelp_urlprotocolinfo
  (JNIEnv *, jobject);

/*
 * Class:     com_onion_ffmpeg_FfmpegHelp
 * Method:    avformatinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_onion_ffmpeg_FfmpegHelp_avformatinfo
  (JNIEnv *, jobject);

/*
 * Class:     com_onion_ffmpeg_FfmpegHelp
 * Method:    avcodecinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_onion_ffmpeg_FfmpegHelp_avcodecinfo
  (JNIEnv *, jobject);

/*
 * Class:     com_onion_ffmpeg_FfmpegHelp
 * Method:    avfilterinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_onion_ffmpeg_FfmpegHelp_avfilterinfo
  (JNIEnv *, jobject);

/*
 * Class:     com_onion_ffmpeg_FfmpegHelp
 * Method:    configurationinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_onion_ffmpeg_FfmpegHelp_configurationinfo
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
